#!/usr/bin/env bash
set -eu

# Establish project state only; runtime availability cannot grant consent.
project_dir="${CLAUDE_PROJECT_DIR:-$PWD}"
if project_root=$(git -C "$project_dir" rev-parse --show-toplevel 2>/dev/null); then
    project_dir=$project_root
fi
contract="$project_dir/.opdev/project.yaml"
if [ -e "$contract" ] || [ -L "$contract" ]; then
    printf '%s\n' '{"hookSpecificOutput":{"hookEventName":"UserPromptSubmit","additionalContext":"The target project has an OpDev contract. Classify actual task scope before runtime lookup: external host/runner/storage/network/account servicing alone uses ordinary operations guidance, even when it supports project CI. Reading job names does not activate development. For project-owned software/configuration/contract changes, read .opdev/project.yaml and AGENTS.md and apply OpDev seamlessly. Isolated disposable local exploration uses proportional preview checks without a production ledger. Retained work can also reach ready for feedback with meaningful focused tests before full integration qualification; do not repeat full suites, final evidence bindings or installed-host trials merely for directional feedback. Read the planning guidance for connected outcome phases and the workflow guidance for scoped continuation. Continue useful independent authorized work through a local blocker; feedback readiness does not automatically end an implementation assignment. Honor actual guided checkpoints and stop boundaries; no expanded release, delegation or spending permission. Required current-source integration and post-merge checks remain at handoff; authorized CI previews do not qualify merging or releasing and cannot bypass reviewed policy. A milestone does not request publication. Invalid/unreadable contracts are errors, not absence. Resolve the runtime only for applicable development/qualification; offer missing setup without installing automatically. Unrelated prompts need no OpDev action."}}'
else
    printf '%s\n' '{"hookSpecificOutput":{"hookEventName":"UserPromptSubmit","additionalContext":"The target project has no OpDev contract. For substantive software planning or implementation, including a design-only folder without Git, offer optional adoption once in the first response after minimal local inspection, before substantive research, planning, or edits. Before the offer, inspect only the supplied design, existing instructions, contract presence and repository state. Checking installed language runtimes or package managers to choose a stack is implementation investigation: offer before those probes, upstream browsing or planning. Ask briefly through an available question tool or plain chat. Honor an earlier decline; if declined or unanswered, continue the requested task without OpDev and do not ask repeatedly. Do not announce or follow OpDev, probe its runtime, initialize, or write a consent marker before acceptance. Routine pull/status/dev-server operations and unrelated prompts need no offer or runtime lookup. An explicit adoption request already supplies assessment consent. Only after activation resolve the runtime and offer any needed setup. An explicit runtime-setup request does not adopt this project."}}'
fi
